### ISSUE TITLE
Graduate from being an experimental project

### ISSUE THREAD

**Issue by hab25** [soupglasses/nix-system-graphics#3]
I've created this issue so people may have something to easily subscribe to so they can be notified when https://github.com/soupglasses/nix-system-graphics/blob/982c9914626bc3c4131164fc18a9750a09120c82/README.md?plain=1#L3C1-L4C250 is no longer true.

(Use case: while this project remains experimental, it is not clear to me that me switching to it from `nixGL` is worth doing.)

Thanks for the project!

**Comment by steinwurf-sofie** [comment]
For some extra context: The experimental status is primarily because it lacks testing on more platforms, especially on older point release models like Ubuntu. However the module names and functionality of these will be kept as stable as possible already. 👍

**Comment by soupglasses** [comment]
For some extra context: The experimental status is primarily because it lacks testing on more platforms, especially on older point release models like Ubuntu. However the module names and functionality of these will be kept as stable as possible already. 👍

**Comment by soupglasses** [comment]
As of the commit https://github.com/soupglasses/nix-system-graphics/commit/26e615e5060743ec7bda1aca2c0b87a450fe5195, it marks the stable-releases of nix-system-graphics.
